# Generated by Django 5.2.5 on 2025-09-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'ordering': ['habilidad'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('NumeroDoc', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='media/qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('numeroDoc', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=100)),
                ('Habilidades', models.ManyToManyField(blank=True, to='Backend.habilidades')),
            ],
            options={
                'verbose_name': 'Personal',
                'ordering': ['id'],
                'unique_together': {('numeroDoc', 'Contraseña')},
            },
        ),
    ]
