# Generated by Django 5.2.5 on 2025-08-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('numeroDoc', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
