# Generated by Django 5.2.5 on 2025-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'ordering': ['habilidad'],
            },
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['Nombre'], 'verbose_name': 'Personal'},
        ),
        migrations.AlterUniqueTogether(
            name='personal',
            unique_together={('numeroDoc', 'Contraseña')},
        ),
    ]
