# Generated by Django 5.2.5 on 2025-09-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
