# Generated by Django 5.2.5 on 2025-08-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_habilidades_alter_personal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='Habilidades',
            field=models.ManyToManyField(blank=True, to='Backend.habilidades'),
        ),
    ]
