# Generated by Django 5.2.5 on 2025-08-10 20:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_personal_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='hoja_Vida',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
