# Generated by Django 5.2.5 on 2025-08-10 20:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_personal_hoja_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='hoja_Vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
