# Generated by Django 5.2.5 on 2025-08-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_personal_hoja_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='hoja_Vida',
        ),
    ]
