# Generated by Django 5.2.5 on 2025-08-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_remove_personal_hoja_vida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['id'], 'verbose_name': 'Personal'},
        ),
    ]
