# Generated by Django 5.2.5 on 2025-08-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_personal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
