# Generated by Django 5.2.5 on 2025-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_usuario_remove_personal_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/qr_codes'),
        ),
    ]
