# Generated by Django 5.2.5 on 2025-08-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_alter_usuario_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Apellido',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Correo',
            field=models.CharField(default=1232, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='NumeroDoc',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
